const types = {
  SET_USER_DATA: "SET_USER_DATA",

  GET_CHAT_LIST_REQUEST: "GET_CHAT_LIST_REQUEST",
  GET_CHAT_LIST_SUCCESS: "GET_CHAT_LIST_SUCCESS",
  GET_CHAT_LIST_FAILED: "GET_CHAT_LIST_FAILED",

  GET_AVAILABLE_USER_REQUEST: "GET_AVAILABLE_USER_REQUEST",
  GET_AVAILABLE_USER_SUCCESS: "GET_AVAILABLE_USER_SUCCESS",
  GET_AVAILABLE_USER_FAILED: "GET_AVAILABLE_USER_FAILED",

  CREATE_NEW_CHAT_REQUEST: "CREATE_NEW_CHAT_REQUEST",
  CREATE_NEW_CHAT_SUCCESS: "CREATE_NEW_CHAT_SUCCESS",
  CREATE_NEW_CHAT_FAILED: "CREATE_NEW_CHAT_FAILED",

  GET_MESSAGE_REQUEST: "GET_MESSAGE_REQUEST",
  GET_MESSAGE_SUCCESS: "GET_MESSAGE_SUCCESS",
  GET_MESSAGE_FAILED: "GET_MESSAGE_SUCCESS",

  SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILED: "SEND_MESSAGE_FAILED",

  NEW_CHAT_EVENT: "NEW_CHAT_EVENT",
  NEW_MESSAGE_RECEIVED: "NEW_MESSAGE_RECEIVED",
};

export default types;
